"""empty message

Revision ID: d6c02958b2bb
Revises: 7e30754dcd42
Create Date: 2020-05-03 12:44:42.283943

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd6c02958b2bb'
down_revision = '7e30754dcd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: "authentications = " toevoegen
    authentications = op.create_table('user_authentication',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_authentication_username'), 'user_authentication', ['username'], unique=True)
    # TODO: "cars = " toevoegen
    cars = op.create_table('car',
                    sa.Column('color', sa.String(length=64), nullable=True),
                    sa.Column('brand', sa.String(length=64), nullable=True),
                    sa.Column('plate', sa.String(length=32), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('owner_id')
                    )
    op.create_index(op.f('ix_car_brand'), 'car', ['brand'], unique=False)
    op.create_index(op.f('ix_car_color'), 'car', ['color'], unique=False)
    op.create_index(op.f('ix_car_plate'), 'car', ['plate'], unique=False)

    # ADDED CODE #
    # TODO: De code hieronder
    # Thanks https://stackoverflow.com/questions/18726527/fetch-table-values-using-alembic-and-update-to-another-table
    conn = op.get_bind()
    res = conn.execute('select id, car_color, car_plate, car_brand from "user"')
    results = res.fetchall()
    old_cars = [{'owner_id': r[0], 'color': r[1], 'plate': r[2], 'brand': r[3]} for r in results]
    op.bulk_insert(cars, old_cars)

    res = conn.execute('select id, username, password_hash from "user"')
    results = res.fetchall()
    old_credentials = [{'id': r[0], 'username': r[1], 'password_hash': r[2]} for r in results]
    op.bulk_insert(authentications, old_credentials)
    # TODO: De code hierboven
    # END OF ADDED CODE #

    op.drop_index('ix_user_car_brand', table_name='user')
    op.drop_index('ix_user_car_color', table_name='user')
    op.drop_index('ix_user_car_plate', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'car_brand')
    op.drop_column('user', 'car_plate')
    op.drop_column('user', 'car_color')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('car_color', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('car_plate', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('car_brand', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_car_plate', 'user', ['car_plate'], unique=True)
    op.create_index('ix_user_car_color', 'user', ['car_color'], unique=False)
    op.create_index('ix_user_car_brand', 'user', ['car_brand'], unique=False)
    op.drop_index(op.f('ix_car_plate'), table_name='car')
    op.drop_index(op.f('ix_car_color'), table_name='car')
    op.drop_index(op.f('ix_car_brand'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_user_authentication_username'), table_name='user_authentication')
    op.drop_table('user_authentication')
    # ### end Alembic commands ###
