"""New database

Revision ID: 24be2fbe7b91
Revises: 
Create Date: 2020-03-05 17:29:58.013831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24be2fbe7b91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('departure_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('departure_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_departure_time'), 'route', ['departure_time'], unique=False)
    op.add_column('user', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_column('user', 'age')
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'firstname')
    op.drop_index(op.f('ix_route_departure_time'), table_name='route')
    op.drop_table('route')
    # ### end Alembic commands ###
