"""Route table

Revision ID: 4ceebfeb21c7
Revises: f345daf88f49
Create Date: 2020-03-03 16:51:23.824318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ceebfeb21c7'
down_revision = 'f345daf88f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('departure_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('departure_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_departure_time'), 'route', ['departure_time'], unique=False)
    op.drop_index('ix_user_age', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_age', 'user', ['age'], unique=False)
    op.drop_index(op.f('ix_route_departure_time'), table_name='route')
    op.drop_table('route')
    # ### end Alembic commands ###
